server:
  port: 8082

spring:
  application:
    name: ms-pedidos360-catalog
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
azure:
  activedirectory:
    audience: ${AZURE_API_AUDIENCE:api://${AZURE_API_CLIENT_ID}}
  datasource:
    url: ${ORACLE_JDBC_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
    username: ${ORACLE_USERNAME:pedidos360}
    password: ${ORACLE_PASSWORD:pedidos360}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG
