server:
  port: 8083

spring:
  application:
    name: ms-digitalfix-notify
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:digitalfix}
    password: ${RABBITMQ_PASSWORD:digitalfix}
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info
