server:
  port: 8085

spring:
  application:
    name: ms-digitalfix-report
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/digitalfix}
    username: ${POSTGRES_USERNAME:digitalfix}
    password: ${POSTGRES_PASSWORD:digitalfix}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
