server:
  port: 8080

spring:
  application:
    name: ms-pedidos360-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0

azure:
  activedirectory:
    tenant-id: ${AZURE_TENANT_ID}
    api-client-id: ${AZURE_API_CLIENT_ID}
    audience: api://${AZURE_API_CLIENT_ID}

pedidos360:
  services:
    workorders:
      base-url: ${WORKORDERS_SERVICE_URL:http://localhost:8081}
    catalog:
      base-url: ${CATALOG_SERVICE_URL:http://localhost:8082}
    notify:
      base-url: ${NOTIFY_SERVICE_URL:http://localhost:8083}
    audit:
      base-url: ${AUDIT_SERVICE_URL:http://localhost:8084}
    report:
      base-url: ${REPORT_SERVICE_URL:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG
